server:
  port: 8084
spring:
  profiles:
    active: prd

---
server:
  port: 8085
spring:
  profiles: dev

---

server:
  port: 8086
spring:
  profiles: prd

---
#person:
#  last-name: 张三
#  age: 20
#  boss: false
#  birth: 2018/05/25
#  maps: {k1: v1,k2: 12}
#  lists:
#   - 小花
#   - 赵楼
#  dog:
#   name: 小狗
#   age: 2
